# IDEA auto formatter is causing trouble
# @formatter:off
name: Hugo Build

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Install Hugo
        run: |
          cd /tmp
          wget https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_extended_0.61.0_Linux-64bit.deb
          sudo dpkg -i hugo*.deb

      - name: Check out
        uses: actions/checkout@v1

      - name: Build
        run: |
          set -Eeuo pipefail
          hugo build
          ls -alh public/
